name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      MPLBACKEND: Agg
      PYTHONIOENCODING: utf-8
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m pip install -U pip
          python -m pip install --prefer-binary -r requirements.txt
      - name: Install dependencies (Ubuntu)
        if: runner.os != 'Windows'
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest -q
